'use client';
import {useRef,useState} from 'react';
import {Smartphone,Tablet,Check,Palette,Plus,Image as ImageIcon,ImagePlus,ImageMinus} from 'lucide-react';
import {Choice} from './scene-controls';
import {DEVICES,COLORS,type Settings} from '@/lib/studio-config';
import type {DivicesController} from '@/lib/use-divices';
export function DevicePanel({c}:{c:DivicesController}){
 const finishPanel=useRef<HTMLElement>(null);
 const [finishDevice,setFinishDevice]=useState<string|null>(null);const finishId=finishDevice??c.device;const finishInfo=DEVICES.find(d=>d.id===finishId)!;const finish=c.preferences.deviceFinishes?.[finishId]??(finishId===c.device?c.settings:c.scenes.find(s=>s.snapshot.device===finishId)?.snapshot.settings??{deviceColor:'#a3a09a',finish:'satin'});
 const info=DEVICES.find(d=>d.id===c.device)!,disabled=c.busy||c.loading;
 return <><div className="device-list">{DEVICES.map(d=>{const artwork=c.deviceArtworks[d.id];return <div key={d.id} className={'device-card device-row '+(c.device===d.id?'selected':'')}><button disabled={disabled} className="device-select" aria-pressed={c.device===d.id} onClick={()=>{setFinishDevice(d.id);c.run(()=>c.chooseDevice(d.id))}}><span className="device-icon">{d.id.includes('pad')||d.id.includes('tab')?<Tablet/>:<Smartphone/>}</span><span className="device-label"><strong>{d.name}</strong><small>{d.detail}</small>{artwork&&<small className="device-default-label" title={artwork.artworkName}>Override · {artwork.artworkName}</small>}</span>{c.device===d.id&&<Check className="check-icon" size={13}/>}</button><div className="device-artwork-actions"><button disabled={disabled} aria-label={'Choose colour for '+d.name} title="Default colour and finish" aria-pressed={finishId===d.id} onClick={()=>{setFinishDevice(d.id);finishPanel.current?.scrollIntoView({behavior:'smooth',block:'nearest'})}}><Palette size={15}/></button><button className={artwork?'has-artwork':''} disabled={disabled} aria-label={(artwork?'Replace':'Add')+' default artwork for '+d.name} title={(artwork?'Replace':'Add')+' default artwork'} onClick={()=>c.openDeviceArtwork(d.id)}><ImagePlus size={15}/></button><button disabled={disabled||!artwork} aria-label={'Remove default artwork for '+d.name} title={artwork?'Remove override and restore scene artworks':'No default artwork set'} onClick={()=>c.removeDeviceArtwork(d.id)}><ImageMinus size={15}/></button></div></div>})}</div>
 <section ref={finishPanel} className="device-finish"><div className="section-heading"><Palette size={16}/><h3>Default device finishes</h3></div><p className="control-hint"><strong>{finishInfo.name}</strong> · Applies to all scenes and new kits for this device. Use the palette icon beside a device to select it.</p><div className="swatches">{COLORS.map(color=><button disabled={disabled} title={color.name} aria-label={color.name+' device colour'} aria-pressed={finish.deviceColor===color.value} key={color.name} style={{background:color.value}} className={finish.deviceColor===color.value?'chosen':''} onClick={()=>c.setDeviceFinish(finishId,{deviceColor:color.value})}/>)}<label className="custom-swatch" title="Custom device colour"><Plus size={15}/><input aria-label="Custom device colour" type="color" disabled={disabled} value={finish.deviceColor} onChange={e=>c.setDeviceFinish(finishId,{deviceColor:e.target.value})}/></label></div><Choice label="Surface" value={finish.finish} disabled={disabled} onChange={v=>c.setDeviceFinish(finishId,{finish:v as Settings['finish']})} options={[{value:'satin',label:'Satin'},{value:'polished',label:'Polished'},{value:'matte',label:'Matte'}]}/></section>
 <section className="screen-section"><div className="section-heading"><ImageIcon size={16}/><h3>Default artworks</h3></div><p className="control-hint">Set an artwork override per device. It appears in every scene, preview and export for that device, including new scenes and Essentials Kits.</p><div className="screen-dimensions"><strong>{info.screenWidth.toLocaleString()} × {info.screenHeight.toLocaleString()} px</strong><span>{info.name} · width × height</span>{info.reference&&<a href={info.reference} target="_blank" rel="noreferrer">Device specifications ↗</a>}</div><button className="secondary-button full artwork-manage" disabled={disabled} onClick={()=>c.openDeviceArtwork()}><ImagePlus size={15}/>Set device artwork overrides</button><p className="privacy">Use the artwork icons beside each device to add, replace or remove its default. Removing an override reveals each scene’s own artwork. Your scene artworks are kept.</p></section></>;
}
