'use client';
import {useRef,useState} from 'react';
import {Box,Save,RotateCcw,Undo2,Redo2,Download,Upload,Sun,Moon,Camera,Move3d,ExternalLink,Layers3,Smartphone} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription} from '@/components/ui/alert-dialog';
import {useDivices} from '@/lib/use-divices';
import {QuickGuide} from './quick-guide';
import {useSceneTools} from '@/lib/scene-tools';
import {DEVICES,CAMERA_PRESETS,type CameraPreset,type SceneFolder} from '@/lib/studio-config';
import {SceneLibraryPanel,folderPath} from './scene-library-panel';
import {SceneControls,Choice} from './scene-controls';
import {DevicePanel} from './device-panel';
import {UnsavedSceneDialog} from './unsaved-scene-dialog';
import {ArtworkDialog} from './artwork-dialog';
import {ResizableWorkspace} from './resizable-panel';
import {ScenePreviewProvider} from './scene-thumbnail';
import {folderDescendants} from '@/lib/scene-library';

export default function DivicesWorkspace(){
 const c=useDivices(),p=c.preferences,disabled=!c.ready||c.busy||c.loading,backupInput=useRef<HTMLInputElement>(null);
 useSceneTools(c);
 const [saveOpen,setSaveOpen]=useState(false),[saveName,setSaveName]=useState(''),[saveFolder,setSaveFolder]=useState('unfiled'),[deleteIds,setDeleteIds]=useState<string[]>([]),[folderDialog,setFolderDialog]=useState<{id?:string;name:string;parentId:string|null;sceneIds?:string[]}|null>(null);
 const [resetOpen,setResetOpen]=useState(false);
 const [renaming,setRenaming]=useState<{id:string;name:string}|null>(null);
 const [deleteFolderIds,setDeleteFolderIds]=useState<string[]>([]),[deleteFolderId,setDeleteFolderId]=useState(''),[deleteFolderContents,setDeleteFolderContents]=useState(true);
 const deletingFolder=c.folders.find(f=>f.id===deleteFolderId),deletingFolderIds=folderDescendants(deleteFolderId,c.folders),folderSceneCount=c.scenes.filter(s=>s.folderId&&deletingFolderIds.has(s.folderId)).length;
 const current=c.scenes.find(s=>s.id===p.activeScene),deviceInfo=DEVICES.find(d=>d.id===c.device)!,name=current?.name??'Untitled scene';
 const openSave=()=>{setSaveName(current?.name??deviceInfo.name+' scene');setSaveFolder(current?.folderId??'unfiled');setSaveOpen(true)};
 const submitSave=(existing=false)=>c.run(async()=>{await c.saveCurrent(saveName,saveFolder==='unfiled'?null:saveFolder,existing?current:undefined);setSaveOpen(false)});
 const folder=(item?:SceneFolder,parentId?:string|null)=>setFolderDialog(item?{...item}:{name:'',parentId:parentId??null,sceneIds:[...c.selected]});
 return <main className="studio-app divices-app">
 <header><div className="brand"><strong className="brand-wordmark"><img src="./divices-logo.svg" alt="Divices" width="86" height="21"/></strong></div><span className="project-name"><span className="project-name-text">{name}</span>{c.dirty&&<span className="unsaved" role="img" aria-label="Unsaved changes" title="Changes not saved to this scene"/>}</span><div className="header-actions"><QuickGuide/><div className="history-controls" role="group" aria-label="Edit history"><button className="secondary-button" aria-label="Undo" aria-keyshortcuts="Control+Z Meta+Z" title={c.undoLabel?'Undo '+c.undoLabel+' (⌘/Ctrl Z)':'Nothing to undo (⌘/Ctrl Z)'} disabled={disabled||!c.undoLabel} onClick={c.undo}><Undo2 size={16}/></button><button className="secondary-button" aria-label="Redo" aria-keyshortcuts="Control+Shift+Z Meta+Shift+Z Control+Y" title={c.redoLabel?'Redo '+c.redoLabel+' (⌘/Ctrl Shift Z)':'Nothing to redo (⌘/Ctrl Shift Z or Ctrl Y)'} disabled={disabled||!c.redoLabel} onClick={c.redo}><Redo2 size={16}/></button></div><div className="backup-controls" role="group" aria-label="Backup controls"><button className="secondary-button backup-header-button" aria-label="Save Backup" title="Save Backup · All scenes, folders, artwork, HDRIs and current settings" disabled={disabled} onClick={c.backup}><Download size={16}/><span>Save Backup</span></button><button className="secondary-button backup-header-button" aria-label="Import Backup" title="Import Backup · Restore a Divices backup" disabled={disabled} onClick={()=>backupInput.current?.click()}><Upload size={16}/><span>Import Backup</span></button></div><button className="secondary-button reset-header-button" aria-label="Full Reset" title="Full Reset · Restore the first-load workspace" disabled={disabled} onClick={()=>setResetOpen(true)}><RotateCcw size={16}/></button><button aria-label="Save scene" className="secondary-button" disabled={disabled} onClick={openSave}><Save size={16}/><span>Save scene</span></button><button aria-label="Export PNG" className="export" disabled={disabled} onClick={c.exportPNG}><Download size={16}/><span>Export PNG</span></button></div></header>
 <ResizableWorkspace preferredWidth={p.leftPanelWidth} onWidth={width=>c.pref('leftPanelWidth',width)}>{handle=><><div className="device-panel-shell"><aside id="left-panel" className="device-panel"><Tabs value={p.leftTab} onValueChange={v=>c.pref('leftTab',v)}><TabsList className="studio-tabs"><TabsTrigger value="scenes"><Layers3 size={15}/>Scenes <span className="tab-count">{c.scenes.length}</span></TabsTrigger><TabsTrigger value="device"><Smartphone size={15}/>Devices</TabsTrigger></TabsList>
 <TabsContent value="scenes"><ScenePreviewProvider deviceArtworks={c.deviceArtworks}><SceneLibraryPanel onRename={scene=>setRenaming({id:scene.id,name:scene.name})} onArrange={drop=>c.run(()=>c.arrangeLibrary(drop))} onAutoSort={mode=>c.run(()=>c.autoSort(mode))} compact={p.compactScenes} onCompact={compact=>c.pref('compactScenes',compact)} scenes={c.scenes} folders={c.folders} selected={c.selected} selectedFolders={c.selectedFolders} active={p.activeScene} busy={disabled} device={c.device} onSelect={id=>c.run(()=>c.loadScene(id))} onToggle={c.toggleSelection} onToggleFolder={c.toggleFolderSelection} onSelectAll={c.selectAll} onClear={c.clearSelection} onSave={openSave} onDelete={id=>{setDeleteFolderIds([]);setDeleteIds([id])}} onDeleteSelected={()=>{setDeleteIds([...c.selected]);setDeleteFolderIds([...c.selectedFolders])}} onDeleteFolder={id=>{setDeleteFolderContents(true);setDeleteFolderId(id)}} onFolder={folder} onMove={(s,id)=>c.run(()=>c.moveScene(s,id))} onMoveMany={(ids,folderId)=>c.run(()=>c.moveScenes(ids,folderId))} onArtwork={()=>c.openArtwork('selected')} onSceneArtwork={id=>c.openArtwork('selected',id)} onKit={c.kit}/></ScenePreviewProvider></TabsContent><TabsContent value="device"><DevicePanel c={c}/></TabsContent></Tabs></aside>{handle}</div>
 <section className={'stage '+(p.splitLights?'split-stage ':'')+(p.lightBackground?'light-stage':'')} style={{backgroundColor:p.lightBackground?'#e9ecf0':c.settings.background}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!disabled)c.upload(e.dataTransfer.files[0])}}>
 <div className="stage-top"><div className="stage-label"><span>{deviceInfo.name}</span><small>{c.viewName}</small></div><div className="camera-readout" aria-label="Live camera position"><span>Orbit <b>{c.liveCamera.azimuth.toFixed(1)}°</b></span><span>Tilt <b>{c.liveCamera.elevation.toFixed(1)}°</b></span><span>Distance <b>{c.liveCamera.distance.toFixed(2)}</b></span><span>Zoom <b>{c.liveCamera.zoom.toFixed(2)}×</b></span></div></div>
 <div ref={c.host} className="viewport" tabIndex={0} aria-label="3D device viewport. Drag to orbit, scroll to zoom."/>
 <button className="viewport-background-toggle" disabled={disabled} aria-label={p.lightBackground?'Use dark viewport background':'Use light viewport background'} title="Viewport only · lighting and export stay unchanged" onClick={()=>c.pref('lightBackground',!p.lightBackground)}>{p.lightBackground?<Moon size={16}/>:<Sun size={16}/>}</button>
 {c.loading&&<div className="loading-pill">Loading device…</div>}
 <div className="view-tools">{(['hero','front','isometric'] as CameraPreset[]).map(id=><button disabled={disabled} key={id} onClick={()=>c.applyPreset(id)} title={CAMERA_PRESETS.find(v=>v.id===id)!.name}>{id==='isometric'?<Box size={16}/>:<Camera size={16}/>}<span>{CAMERA_PRESETS.find(v=>v.id===id)!.name}</span></button>)}<span/><button disabled={disabled} className={p.splitLights?'tool-active':''} aria-label={p.splitLights?'Close split lighting view':'Light positions'} aria-pressed={p.splitLights} onClick={()=>{c.pref('splitLights',!p.splitLights);c.pref('rightTab','lights')}}><Move3d size={17}/><span>{p.splitLights?'Close split':'Light positions'}</span></button></div>
 <div className="stage-bottom">{c.message&&<span className={'render-status '+(c.error?'error':'')} role={c.error?'alert':'status'}>{c.message}</span>}</div>{c.progress&&<div className="batch-overlay"><Download size={24}/><strong>{c.progress}</strong><p>Your current scene will be restored when the export finishes.</p><button className="secondary-button" onClick={c.cancelBatch}>Cancel remaining</button></div>}
 </section><SceneControls c={c}/></>}</ResizableWorkspace>
 <footer><span className="creator-links">Created by Jin Yoshida <a href="https://github.com/jinyoshida01" target="_blank" rel="noreferrer"><ExternalLink size={13}/>GitHub</a><a href="https://jinyoshida.me" target="_blank" rel="noreferrer"><ExternalLink size={12}/>Portfolio</a></span><span>THREE.JS / REAL-TIME 3D</span></footer>
 {c.artworkDraft&&<ArtworkDialog c={c}/> }
 {c.pendingLeave&&<UnsavedSceneDialog c={c}/>}
 <input ref={backupInput} type="file" hidden accept=".json" onChange={e=>{c.readBackup(e.target.files?.[0]);e.target.value=''}}/>
 <Dialog open={saveOpen} onOpenChange={setSaveOpen}><DialogContent className="save-dialog"><DialogHeader><DialogTitle>Save scene</DialogTitle><DialogDescription>Update this scene to keep all changes, including artwork. New scenes copy the current setup with a green screen. Device artwork overrides apply when set.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();submitSave()}}><label htmlFor="scene-name">Scene name</label><input id="scene-name" required maxLength={80} value={saveName} onChange={e=>setSaveName(e.target.value)}/><Choice label="Folder" value={saveFolder} onChange={setSaveFolder} disabled={c.busy} options={[{value:'unfiled',label:'Unfiled'},...c.folders.map(f=>({value:f.id,label:folderPath(f.id,c.folders)}))]}/><div className="dialog-actions">{current&&<button type="button" className="secondary-button" disabled={c.busy} onClick={()=>submitSave(true)}>Update scene</button>}<button className="export" disabled={c.busy||!saveName.trim()} type="submit">Save new scene</button></div></form></DialogContent></Dialog>
 <Dialog open={!!renaming} onOpenChange={open=>{if(!open)setRenaming(null)}}><DialogContent className="save-dialog"><DialogHeader><DialogTitle>Rename scene</DialogTitle><DialogDescription>Give this saved scene a new name.</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(renaming)c.run(async()=>{await c.renameScene(renaming.id,renaming.name);setRenaming(null)})}}><label htmlFor="rename-scene-name">Scene name</label><input id="rename-scene-name" autoFocus required maxLength={80} value={renaming?.name??''} onFocus={e=>e.currentTarget.select()} onChange={e=>setRenaming(value=>value?{...value,name:e.target.value}:null)}/><div className="dialog-actions"><button className="secondary-button" type="button" onClick={()=>setRenaming(null)}>Cancel</button><button className="export" disabled={c.busy||!renaming?.name.trim()} type="submit">Rename scene</button></div></form></DialogContent></Dialog>
 <Dialog open={!!folderDialog} onOpenChange={v=>{if(!v)setFolderDialog(null)}}><DialogContent className="save-dialog"><DialogHeader><DialogTitle>{folderDialog?.id?'Rename folder':'New folder'}</DialogTitle><DialogDescription>{folderDialog?.parentId?'Inside '+folderPath(folderDialog.parentId,c.folders):'Organise your scenes.'}{!folderDialog?.id&&!!folderDialog?.sceneIds?.length&&` ${folderDialog.sceneIds.length} selected scenes will move into this folder.`}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();if(folderDialog)c.run(async()=>{await c.saveFolder({id:folderDialog.id??crypto.randomUUID(),name:folderDialog.name,parentId:folderDialog.parentId},folderDialog.id?[]:folderDialog.sceneIds);setFolderDialog(null)})}}><label htmlFor="folder-name">Folder name</label><input id="folder-name" required maxLength={80} value={folderDialog?.name??''} onChange={e=>setFolderDialog(f=>f?{...f,name:e.target.value}:f)}/><button className="export wide" disabled={c.busy||!folderDialog?.name.trim()}>Save folder</button></form></DialogContent></Dialog>
 <AlertDialog open={!!(deleteIds.length+deleteFolderIds.length)} onOpenChange={v=>{if(!v){setDeleteIds([]);setDeleteFolderIds([])}}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete {deleteFolderIds.length?'selected scenes and folders':deleteIds.length===1?'scene':deleteIds.length+' scenes'}?</AlertDialogTitle><AlertDialogDescription>{deleteFolderIds.length?'Selected folders and all their contents, along with any other selected scenes':deleteIds.length===1?'“'+c.scenes.find(s=>s.id===deleteIds[0])?.name+'”':deleteIds.length+' selected scenes'} will be removed from the library. The current view stays open. Use Undo in the header to restore it during this session.</AlertDialogDescription></AlertDialogHeader><div className="dialog-actions"><button className="secondary-button" onClick={()=>{setDeleteIds([]);setDeleteFolderIds([])}}>Cancel</button><button disabled={c.busy} className="danger-button" onClick={()=>c.run(async()=>{await c.removeScenes(deleteIds,deleteFolderIds);setDeleteIds([]);setDeleteFolderIds([])})}>Delete {deleteFolderIds.length?'all selected':deleteIds.length===1?'scene':deleteIds.length+' scenes'}</button></div></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!deleteFolderId} onOpenChange={v=>{if(!v)setDeleteFolderId('')}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete folder?</AlertDialogTitle><AlertDialogDescription>“{deletingFolder?.name}” and its subfolders will be removed. Its {folderSceneCount} scenes will also be deleted unless you uncheck the option below. Use Undo in the header to restore it during this session.</AlertDialogDescription></AlertDialogHeader>{folderSceneCount>0&&<label className="check-row"><input type="checkbox" checked={deleteFolderContents} onChange={e=>setDeleteFolderContents(e.target.checked)}/>Delete all {folderSceneCount} scenes inside</label>}<div className="dialog-actions"><button className="secondary-button" disabled={c.busy} onClick={()=>setDeleteFolderId('')}>Cancel</button><button className="danger-button" disabled={c.busy} onClick={()=>c.run(async()=>{await c.removeFolder(deleteFolderId,deleteFolderContents);setDeleteFolderId('')})}>{deleteFolderContents?'Delete folder and scenes':'Delete folder only'}</button></div></AlertDialogContent></AlertDialog>
 <AlertDialog open={resetOpen} onOpenChange={open=>{if(!c.busy)setResetOpen(open)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Reset Divices completely?</AlertDialogTitle><AlertDialogDescription>This removes all saved scenes, folders, uploaded artwork and HDRIs, device overrides, preferences, and undo history in this browser. Divices will reload with the default Generic Smartphone Essentials Kit and green screens. Save a backup first if you want to keep your work. This cannot be undone.</AlertDialogDescription></AlertDialogHeader><div className="dialog-actions"><button autoFocus className="secondary-button" disabled={c.busy} onClick={()=>setResetOpen(false)}>Cancel</button><button className="secondary-button" disabled={c.busy} onClick={c.backup}>Save Backup</button><button className="danger-button" disabled={c.busy} onClick={c.resetWorkspace}>{c.busy?'Please wait…':'Reset Everything'}</button></div></AlertDialogContent></AlertDialog>
 <AlertDialog open={!!c.pendingBackup} onOpenChange={v=>{if(!v)c.setPendingBackup(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Restore this backup?</AlertDialogTitle><AlertDialogDescription>This replaces the library with {c.pendingBackup?.scenes.length} scenes and {c.pendingBackup?.folders.length} folders, and restores the saved workspace. Save a backup of your current library first if you need to keep it.</AlertDialogDescription></AlertDialogHeader><div className="dialog-actions"><button className="secondary-button" disabled={c.busy} onClick={()=>c.setPendingBackup(null)}>Cancel</button><button className="export" disabled={c.busy} onClick={c.restoreBackup}>Restore backup</button></div></AlertDialogContent></AlertDialog>
 </main>;
}
