'use client';
import {useState} from 'react';
import {CircleHelp,Layers3,ImagePlus,Camera,Lightbulb,Eclipse,Download,Save,ArrowLeft,ArrowRight} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';

const chapters=[
 {name:'Scenes',icon:Layers3,title:'Start with a scene',intro:'Your first workspace opens with the Generic Smartphone Essentials Kit, ready to customise.',items:[['Explore the kit','Choose a scene on the left to try its camera composition, lighting and HDRI setup. Load more Essentials Kits for any device.'],['Make it yours','Save scene captures the full setup. Update the current scene or save a new one; use its pencil or actions menu to rename it.'],['Keep things organised','Drag scenes and folders to rearrange or nest them. Use Reorder for automatic sorting, folder checkboxes for bulk actions, and Compact for a smaller list.']],tip:'Drag the left panel divider to give your scene previews more room.'},
 {name:'Artwork & devices',icon:ImagePlus,title:'Put your artwork on screen',intro:'Choose exactly where an artwork appears, from a single scene to an entire device collection.',items:[['Individual scenes','Use the small artwork icon beside a scene, or Add screen artworks to choose scenes grouped by folder.'],['Apply to a collection','The artwork assignment options let you target selected scenes, a folder, a specific device or all scenes.'],['Device defaults','In Devices, the artwork icon sets an override for that device. Remove it to reveal individual scene artworks again. The palette icon changes Default device finishes.']],tip:'New scenes and kits start with green screens. A device artwork override takes priority when one is set.'},
 {name:'Camera',icon:Camera,title:'Find your angle',intro:'Move around the device directly in the viewport, or start with a prepared camera angle.',items:[['Orbit and zoom','Drag the viewport to rotate around the device. Scroll to zoom; the live camera numbers update as you move.'],['Try a preset','Camera presets and the angle buttons pair a composition with a matching lighting setup. Adjust the camera afterward to refine it.'],['Shape the perspective','Field of view changes the sense of depth. Lower values give a flatter product view; higher values make nearby features feel larger. Try isometric for a graphic, even perspective.']],tip:'The light/dark viewport background button changes the backdrop only, leaving the lighting and export unchanged.'},
 {name:'Lights',icon:Lightbulb,title:'Sculpt the edges with light',intro:'Light position, size and strength can dramatically change the look of the same device and finish.',items:[['Position the lights','Open Light positions for a split view. Click a light to select it and drag its axes, or use the XYZ sliders in the Lights panel.'],['Control the highlight','Larger light panels tend to create broader, softer highlights. Narrow panels create slimmer reflections that help define the rim. Adjust intensity in small steps.'],['Keep the screen clear','Aim lights across the edges and rounded corners, rather than directly at the front. Keep screen reflections disabled when you want artwork free from glare.']],tip:'If the sides look washed out, reposition or soften the light before raising exposure. Aim for a fine rim and a gentle highlight around each corner.'},
 {name:'HDRI',icon:Eclipse,title:'Design the reflections',intro:'HDRI is the environment reflected in the device. It can change the perceived material and shape just as much as the lights.',items:[['Start with an environment','Choose an HDRI preset, upload your own, or select No HDRI. Rotation moves its reflections around the device; intensity changes their strength.'],['Paint with white and black','In the HDRI editor, white circles and squares add bright reflection areas. Black shapes mask parts of the environment, helping create contrast and quieter surfaces. Adjust size, brightness and softness.'],['Edit several shapes','Drag a box on empty canvas to select shapes, or Shift-click to add to a selection. Alt-drag starts a box over a shape. Move the group together; press Delete to remove it.']],tip:'HDRI edits update live and save to the active saved scene. Small changes can turn a flat-looking surface into a convincing metal or glass finish.'},
 {name:'Look & export',icon:Download,title:'Finish and export',intro:'Refine the final look, then export a single scene or a complete set.',items:[['Polish the render','Use Product tone mapping for the default look, adjust exposure carefully, and add an optional outline glow with your chosen colour.'],['Export one or many','Export PNG saves the current view. Select multiple scenes to reveal bulk export in the right-hand Export panel, or export an Essentials Kit directly.'],['Choose your output','Transparent PNG and the highest resolution are the defaults. The export keeps the full device in frame. Export naming lets you customise names; bulk images use their folder as a prefix.']],tip:'For example, scene 01 in “Samsung Galaxy 24” exports as Samsung-Galaxy-24_01.png in a multi-scene export.'},
 {name:'Save & restore',icon:Save,title:'Keep your work',intro:'Your workspace is retained in this browser. Saved scenes let you return to a complete setup.',items:[['Update the scene','Use Save scene after changing its camera, lights or other settings. A warning helps you save unsaved changes before switching to another scene. HDRI edits save to the active scene as you work.'],['Undo and redo','Use the header arrows, Cmd/Ctrl-Z and Cmd/Ctrl-Shift-Z. History is available during the current session.'],['Make a portable backup','Save a workspace backup from the Scenes panel to keep your scenes, folders, artwork and settings together. Import it to restore the workspace or move to another browser.']],tip:'Browser storage is local to that browser. Keep a backup before clearing browser data or moving to another computer.'},
];

export function QuickGuide(){
 const [open,setOpen]=useState(false),[step,setStep]=useState(0),chapter=chapters[step],Icon=chapter.icon;
 return <Dialog open={open} onOpenChange={value=>{setOpen(value);if(value)setStep(0)}}>
  <DialogTrigger asChild><button className="quick-guide-trigger" aria-label="Open quick guide" title="Quick guide"><CircleHelp size={19}/></button></DialogTrigger>
  <DialogContent className="quick-guide-dialog">
   <DialogHeader><DialogTitle>Divices quick guide</DialogTitle><DialogDescription>From your first scene to a finished render.</DialogDescription></DialogHeader>
   <div className="quick-guide-layout">
    <nav className="quick-guide-nav" aria-label="Guide chapters">{chapters.map((item,index)=><button key={item.name} aria-current={step===index?'step':undefined} onClick={()=>setStep(index)}><item.icon size={16}/>{item.name}</button>)}</nav>
    <div className="quick-guide-page" aria-live="polite" aria-atomic="true">
     <span className="quick-guide-symbol"><Icon size={25}/></span><h2>{chapter.title}</h2><p className="quick-guide-intro">{chapter.intro}</p>
     <dl>{chapter.items.map(([title,body])=><div key={title}><dt>{title}</dt><dd>{body}</dd></div>)}</dl>
     <p className="quick-guide-tip">{chapter.tip}</p>
    </div>
   </div>
   <div className="quick-guide-footer"><span>{step+1} / {chapters.length}</span><div><button className="secondary-button" disabled={step===0} onClick={()=>setStep(step-1)}><ArrowLeft size={15}/>Back</button><button className="export" onClick={()=>step===chapters.length-1?setOpen(false):setStep(step+1)}>{step===chapters.length-1?'Done':'Next'}{step<chapters.length-1&&<ArrowRight size={15}/>}</button></div></div>
  </DialogContent>
 </Dialog>;
}
