'use client';
import {useRef,useState,type PointerEvent} from 'react';
import {ChevronDown,ChevronRight,Save,Download,Folder,FolderPlus,Plus,Pencil,Trash2,Upload,Package,Image as ImageIcon,List,LayoutGrid,MoreHorizontal,ArrowDownUp,ArrowDownAZ,ArrowUpAZ,Clock,Smartphone} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {manualOrder,type LibraryDrop,type SortMode} from '@/lib/library-order';
import {KIT_VIEWS} from '@/lib/essentials-kit';
import {folderDescendants} from '@/lib/scene-library';
import {folderScenes,selectionState} from '@/lib/artwork-scopes';
import {DEVICES,type SavedScene,type SceneFolder} from '@/lib/studio-config';
import {SceneThumbnail} from './scene-thumbnail';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuSub,DropdownMenuSubTrigger,DropdownMenuSubContent} from '@/components/ui/dropdown-menu';

export function folderPath(id:string|null|undefined,folders:SceneFolder[]):string {if(!id)return 'Unfiled';const folder=folders.find(f=>f.id===id);return folder?(folder.parentId?folderPath(folder.parentId,folders)+' / ':'')+folder.name:'Unfiled'}
interface Props {onRename:(scene:SavedScene)=>void;onArrange:(drop:LibraryDrop)=>void;onAutoSort:(mode:SortMode)=>void;compact:boolean;onCompact:(value:boolean)=>void;scenes:SavedScene[];folders:SceneFolder[];selected:Set<string>;selectedFolders:Set<string>;active:string;busy:boolean;device:string;onSelect:(id:string)=>void;onToggle:(id:string)=>void;onToggleFolder:(id:string)=>void;onSelectAll:()=>void;onClear:()=>void;onSave:()=>void;onDelete:(id:string)=>void;onDeleteSelected:()=>void;onDeleteFolder:(id:string)=>void;onFolder:(folder?:SceneFolder,parentId?:string|null)=>void;onMove:(scene:SavedScene,folderId:string|null)=>void;onMoveMany:(ids:string[],folderId:string|null)=>void;onBackup:()=>void;onImport:()=>void;onArtwork:()=>void;onSceneArtwork:(id:string)=>void;onKit:(device:string,action:'load'|'export')=>void}
export function SceneLibraryPanel(p:Props){
 const [collapsed,setCollapsed]=useState(new Set<string>()),[kitDevice,setKitDevice]=useState(p.device),[dropTarget,setDropTarget]=useState<Pick<LibraryDrop,'targetKind'|'targetId'|'placement'>|null>(null),[dragCount,setDragCount]=useState(0),[dragPoint,setDragPoint]=useState({x:0,y:0});
 const drag=useRef<{pointerId:number;x:number;y:number;kind:'scene'|'folder';ids:string[];active:boolean}|null>(null),suppressClick=useRef(false);
 const endDrag=()=>{drag.current=null;setDragCount(0);setDropTarget(null);setTimeout(()=>{suppressClick.current=false},0)};
 const targetAt=(x:number,y:number):Pick<LibraryDrop,'targetKind'|'targetId'|'placement'>|null=>{
  const el=document.elementFromPoint(x,y)?.closest<HTMLElement>('[data-order-kind]');if(!el)return null;
  const kind=el.dataset.orderKind as LibraryDrop['targetKind'],rect=el.getBoundingClientRect(),fraction=(y-rect.top)/rect.height;
  if(drag.current?.kind==='folder'&&kind==='scene')return null;
  return {targetKind:kind,targetId:el.dataset.orderId??'',placement:kind==='root'?'inside':kind==='folder'&&(drag.current?.kind==='scene'||fraction>.25&&fraction<.75)?'inside':fraction<.5?'before':'after'};
 };
 const startDrag=(e:PointerEvent<HTMLButtonElement>,id:string,kind:'scene'|'folder')=>{if(p.busy||e.button!==0)return;suppressClick.current=false;drag.current={pointerId:e.pointerId,x:e.clientX,y:e.clientY,kind,ids:kind==='scene'&&p.selected.has(id)?p.scenes.filter(s=>p.selected.has(s.id)).sort(manualOrder).map(s=>s.id):[id],active:false};e.currentTarget.setPointerCapture(e.pointerId)};
 const moveDrag=(e:PointerEvent<HTMLButtonElement>)=>{const current=drag.current;if(!current||current.pointerId!==e.pointerId)return;if(!current.active&&Math.hypot(e.clientX-current.x,e.clientY-current.y)>5){current.active=true;suppressClick.current=true;setDragCount(current.ids.length)}if(!current.active)return;e.preventDefault();setDragPoint({x:e.clientX,y:e.clientY});setDropTarget(targetAt(e.clientX,e.clientY));const panel=e.currentTarget.closest('aside');if(panel){const rect=panel.getBoundingClientRect();const scroll=panel.scrollHeight>panel.clientHeight?panel:document.scrollingElement;if(e.clientY<Math.max(0,rect.top)+40)scroll?.scrollBy(0,-14);else if(e.clientY>Math.min(window.innerHeight,rect.bottom)-40)scroll?.scrollBy(0,14)}};
 const finishDrag=(e:PointerEvent<HTMLButtonElement>)=>{const current=drag.current;if(current?.active&&!p.busy){const target=targetAt(e.clientX,e.clientY);if(target){p.onArrange({kind:current.kind,ids:current.ids,...target});if(target.placement==='inside')setCollapsed(old=>{const next=new Set(old);next.delete(target.targetId);return next})}}if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);endDrag()};
 const dropClass=(kind:LibraryDrop['targetKind'],id:string)=>dropTarget?.targetKind===kind&&dropTarget.targetId===id?' drop-'+dropTarget.placement:'';
 const toggleFolder=(id:string)=>setCollapsed(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next});
 const sceneMenu=(s:SavedScene)=><DropdownMenu><DropdownMenuTrigger className="scene-more" disabled={p.busy} aria-label={'Actions for '+s.name}><MoreHorizontal size={16}/></DropdownMenuTrigger><DropdownMenuContent className="scene-actions-menu" align="end"><DropdownMenuItem onSelect={()=>p.onRename(s)}><Pencil size={14}/>Rename scene</DropdownMenuItem><DropdownMenuItem onSelect={()=>p.onSceneArtwork(s.id)}><ImageIcon size={14}/>Add screen artwork</DropdownMenuItem><DropdownMenuSub><DropdownMenuSubTrigger><Folder size={14}/>Move to folder</DropdownMenuSubTrigger><DropdownMenuSubContent className="scene-actions-menu"><DropdownMenuItem onSelect={()=>p.onMove(s,null)}>Unfiled</DropdownMenuItem>{p.folders.map(f=><DropdownMenuItem key={f.id} onSelect={()=>p.onMove(s,f.id)}>{folderPath(f.id,p.folders)}</DropdownMenuItem>)}</DropdownMenuSubContent></DropdownMenuSub><DropdownMenuItem onSelect={()=>p.onDelete(s.id)}><Trash2 size={14}/>Delete scene</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
 const folderMenu=(f:SceneFolder)=><DropdownMenu><DropdownMenuTrigger className="scene-more" disabled={p.busy} aria-label={'Actions for folder '+f.name}><MoreHorizontal size={16}/></DropdownMenuTrigger><DropdownMenuContent className="scene-actions-menu" align="end"><DropdownMenuItem onSelect={()=>p.onFolder(f)}><Pencil size={14}/>Rename folder</DropdownMenuItem><DropdownMenuItem onSelect={()=>p.onFolder(undefined,f.id)}><Plus size={14}/>Add subfolder</DropdownMenuItem><DropdownMenuItem onSelect={()=>p.onDeleteFolder(f.id)}><Trash2 size={14}/>Delete folder</DropdownMenuItem></DropdownMenuContent></DropdownMenu>;
 const sceneRow=(s:SavedScene)=><div data-order-kind="scene" data-order-id={s.id} data-scene-id={s.id} className={'scene-record '+dropClass('scene',s.id)+' '+(p.active===s.id?'active ':'')+(p.selected.has(s.id)?'is-selected':'')} key={s.id}>
  <div className="scene-record-main"><Checkbox className="scene-checkbox" aria-label={'Select '+s.name} checked={p.selected.has(s.id)} disabled={p.busy} onCheckedChange={()=>p.onToggle(s.id)}/><button draggable={false} onPointerDown={e=>startDrag(e,s.id,'scene')} onPointerMove={moveDrag} onPointerUp={finishDrag} onPointerCancel={endDrag} onLostPointerCapture={endDrag} className="scene-load" title={s.name+' · '+(s.snapshot.artwork?s.snapshot.artworkName:'Green screen')} disabled={p.busy} onClick={()=>{if(suppressClick.current){suppressClick.current=false;return}p.onSelect(s.id)}}><SceneThumbnail scene={s}/><span className="scene-description"><strong>{s.name}</strong><small>{DEVICES.find(d=>d.id===s.snapshot.device)?.name}</small><small className="scene-artwork-name" title={s.snapshot.artwork?s.snapshot.artworkName:'Green screen'}>{s.snapshot.artwork?s.snapshot.artworkName:'Green screen'}</small></span></button><button className="scene-artwork-button" disabled={p.busy} aria-label={'Add screen artwork to '+s.name} title="Add screen artwork" onClick={()=>p.onSceneArtwork(s.id)}><ImageIcon size={14}/></button>{p.compact?sceneMenu(s):<><button className="scene-more" aria-label={'Rename '+s.name} disabled={p.busy} onClick={()=>p.onRename(s)}><Pencil size={14}/></button><button className="scene-delete" disabled={p.busy} aria-label={'Delete '+s.name} onClick={()=>p.onDelete(s.id)}><Trash2 size={16}/></button></>}</div>
  {!p.compact&&<Select value={s.folderId??'unfiled'} onValueChange={v=>p.onMove(s,v==='unfiled'?null:v)} disabled={p.busy}><SelectTrigger className="scene-folder-select" aria-label={'Folder for '+s.name}><Folder size={12}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="unfiled">Unfiled</SelectItem>{p.folders.map(f=><SelectItem value={f.id} key={f.id}>{folderPath(f.id,p.folders)}</SelectItem>)}</SelectContent></Select>}
 </div>;
 const tree=(parentId:string|null,depth=0)=>p.folders.filter(f=>f.parentId===parentId).sort(manualOrder).map(f=>{const ids=folderScenes(f.id,p.scenes,p.folders).map(s=>s.id);return <div className="scene-folder" key={f.id} style={{marginLeft:depth?10:0}}>
  <div className={'folder-heading '+dropClass('folder',f.id)} data-order-kind="folder" data-order-id={f.id} data-folder-id={f.id} title={dragCount?'Drop '+dragCount+' scenes into '+f.name:undefined}><Checkbox className="scene-checkbox" aria-label={'Select folder '+f.name} title="Select folder and all contents" checked={p.selectedFolders.has(f.id)?true:selectionState(ids,p.selected)||[...folderDescendants(f.id,p.folders)].some(id=>p.selectedFolders.has(id))?'indeterminate':false} disabled={p.busy} onCheckedChange={()=>p.onToggleFolder(f.id)}/><button className="folder-toggle" disabled={p.busy} onPointerDown={e=>startDrag(e,f.id,'folder')} onPointerMove={moveDrag} onPointerUp={finishDrag} onPointerCancel={endDrag} onLostPointerCapture={endDrag} title={folderPath(f.id,p.folders)} onClick={()=>{if(suppressClick.current)return;toggleFolder(f.id)}} aria-expanded={!collapsed.has(f.id)}>{collapsed.has(f.id)?<ChevronRight size={14}/>:<ChevronDown size={14}/>}<Folder size={14}/><span>{f.name}</span></button>{p.compact?folderMenu(f):<><button className="icon-button" disabled={p.busy} aria-label={'Rename '+f.name} onClick={()=>p.onFolder(f)}><Pencil size={13}/></button><button className="icon-button" disabled={p.busy} aria-label={'Add folder inside '+f.name} onClick={()=>p.onFolder(undefined,f.id)}><Plus size={14}/></button><button className="icon-button folder-delete" disabled={p.busy} aria-label={'Delete folder '+f.name} onClick={()=>p.onDeleteFolder(f.id)}><Trash2 size={13}/></button></>}</div>
  {!collapsed.has(f.id)&&<div>{p.scenes.filter(s=>s.folderId===f.id).sort(manualOrder).map(sceneRow)}{tree(f.id,depth+1)}</div>}
 </div>});
 return <div className={'scene-library '+(p.compact?'compact-scenes':'preview-scenes')}>
  {!!dragCount&&<div className="scene-drag-badge" style={{left:dragPoint.x+14,top:dragPoint.y+14}}><Folder size={14}/>{dragCount} {drag.current?.kind==='folder'?'folder':dragCount===1?'scene':'scenes'}</div>}
  <div className="section-heading"><Folder size={16}/><h3>Your Scenes</h3><button className="scene-view-toggle" aria-label={p.compact?'Switch to Preview View':'Switch to Compact View'} title={p.compact?'Switch to Preview View':'Switch to Compact View'} onClick={()=>p.onCompact(!p.compact)}>{p.compact?<LayoutGrid size={16}/>:<List size={16}/>}</button></div><button className="secondary-button full save-scene-left" disabled={p.busy} onClick={p.onSave}><Save size={15}/>Save Scene</button>

  <DropdownMenu><DropdownMenuTrigger className="secondary-button library-sort-button" disabled={p.busy} aria-label="Reorder scenes and folders"><ArrowDownUp size={15}/><span>Reorder</span><ChevronDown size={14}/></DropdownMenuTrigger><DropdownMenuContent className="scene-actions-menu library-sort-menu" align="start" sideOffset={6}><div className="library-sort-caption">Sort within each folder</div><DropdownMenuItem onSelect={()=>p.onAutoSort('name')}><ArrowDownAZ size={16}/><span>Name A–Z <small>Scene numbers in order</small></span></DropdownMenuItem><DropdownMenuItem onSelect={()=>p.onAutoSort('name-desc')}><ArrowUpAZ size={16}/><span>Name Z–A <small>Reverse name order</small></span></DropdownMenuItem><DropdownMenuItem onSelect={()=>p.onAutoSort('newest')}><Clock size={16}/><span>Newest first <small>Recently created scenes</small></span></DropdownMenuItem><DropdownMenuItem onSelect={()=>p.onAutoSort('device')}><Smartphone size={16}/><span>Device, then name <small>Group matching devices</small></span></DropdownMenuItem></DropdownMenuContent></DropdownMenu>
<div className="library-actions"><button className="secondary-button" disabled={p.busy} onClick={()=>p.onFolder()}><FolderPlus size={14}/>Add Folder</button><button className="text-button" disabled={p.busy||(!p.scenes.length&&!p.folders.length)} onClick={p.selected.size||p.selectedFolders.size?p.onClear:p.onSelectAll}>{p.selected.size||p.selectedFolders.size?'Clear':'Select all'}</button></div>
  <button className="secondary-button full add-scene-artworks" disabled={p.busy||!p.scenes.length} onClick={p.onArtwork}><ImageIcon size={16}/>Add screen artworks</button>
  {!!(p.selected.size+p.selectedFolders.size)&&<div className="bulk-scene-actions"><p className="selection-summary">{p.selected.size} {p.selected.size===1?'scene':'scenes'}{p.selectedFolders.size?` · ${p.selectedFolders.size} ${p.selectedFolders.size===1?'folder':'folders'}`:""} selected</p><button className="danger-button full" disabled={p.busy} onClick={p.onDeleteSelected}><Trash2 size={15}/>Delete all selected</button></div>}
  {!p.scenes.length&&!p.folders.length&&<p className="empty-scenes">Save your setup or load an Essentials Kit. Scenes keep the device, artwork, camera and lighting together.</p>}
  <p className="scene-drag-hint">Drag between rows to reorder. Drop onto a folder to move inside. Selected scenes move together.</p><div className="scene-tree">{tree(null)}<div className="unfiled-drop"><div className={'unfiled-heading'+dropClass('root','')} data-order-kind="root" data-order-id=""><Folder size={13}/>Unfiled</div>{p.scenes.filter(s=>!s.folderId).sort(manualOrder).map(sceneRow)}</div></div>
  <section className="kit-panel"><div className="section-heading"><Package size={16}/><h3>Essentials Kit</h3><span className="tag">{KIT_VIEWS.length}</span></div><p className="control-hint">0°, 45° and 315°, plus nine dynamic compositions, including a bottom-up close-up. Each includes its own lighting.</p>
   <Select value={kitDevice} onValueChange={setKitDevice} disabled={p.busy}><SelectTrigger aria-label="Essentials Kit device"><SelectValue/></SelectTrigger><SelectContent>{DEVICES.map(d=><SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>)}</SelectContent></Select>
   <div className="kit-actions"><button className="secondary-button full" disabled={p.busy} onClick={()=>p.onKit(kitDevice,'load')}><Plus size={15}/>Load as scenes</button><button className="secondary-button full" disabled={p.busy} onClick={()=>p.onKit(kitDevice,'export')}><Download size={15}/>Export kit · ZIP</button></div><p className="control-hint">Starts with green screens unless a device artwork override is set. Add individual artwork after loading. Export size follows your export settings.</p>
  </section>
  <section className="backup-panel"><h3>Backup & restore</h3><p className="control-hint">Includes all scenes, folders, artwork, HDRIs and your current settings.</p><div className="kit-actions"><button className="secondary-button full" disabled={p.busy} onClick={p.onBackup}><Download size={14}/>Save backup</button><button className="secondary-button full" disabled={p.busy} onClick={p.onImport}><Upload size={14}/>Import backup</button></div><p className="privacy">Saved automatically in this browser. Keep a backup before clearing browser data.</p></section>
 </div>;
}
