'use client';
import {useRef} from 'react';
import {HDRIEditor} from './hdri-editor';
import {ExportNamingControls} from './export-naming-controls';
import {Camera,Move3d,RotateCcw,Upload,Sun,Orbit,SlidersHorizontal,Download,ChevronDown,ChevronUp} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Collapsible,CollapsibleTrigger,CollapsibleContent} from '@/components/ui/collapsible';
import {CAMERA_PRESETS,ORBIT_ANGLES,ENVIRONMENTS,settingsFor,type Settings,type Vec3} from '@/lib/studio-config';
import type {DivicesController} from '@/lib/use-divices';

export function Choice({label,value,onChange,options,disabled=false}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];disabled?:boolean}){return <div className="select-row"><label>{label}</label><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
export function SceneControls({c}:{c:DivicesController}){
 const hdrFile=useRef<HTMLInputElement>(null),{settings:s,preferences:p}=c,disabled=c.busy||c.loading,light=s.lights.find(l=>l.id===p.selectedLight)!;
 const range=(label:string,value:number,change:(v:number)=>void,min:number,max:number,step:number,suffix='')=><div className="range"><div><label>{label}</label><output>{value.toFixed(step<1?1:0)}{suffix}</output></div><Slider aria-label={label} disabled={disabled} value={[value]} min={min} max={max} step={step} onValueChange={v=>change(v[0])}/></div>;
 const choice=(label:string,value:string,onChange:(v:string)=>void,options:{value:string;label:string}[])=><Choice {...{label,value,onChange,options,disabled}}/>;
 return <aside className="settings-panel"><Tabs value={p.rightTab} onValueChange={v=>c.pref('rightTab',v)} className="settings-tabs"><TabsList className="studio-tabs"><TabsTrigger value="lights"><Sun size={14}/>Lights</TabsTrigger><TabsTrigger value="look"><SlidersHorizontal size={14}/>Look</TabsTrigger><TabsTrigger value="camera"><Camera size={14}/>Camera</TabsTrigger></TabsList><div className="settings-scroll">
 <TabsContent value="lights"><section><div className="section-heading"><Sun size={16}/><h3>Scene Lights</h3></div><div className="light-select">{s.lights.map(l=><button disabled={disabled} key={l.id} className={p.selectedLight===l.id?'selected':''} onClick={()=>c.pref('selectedLight',l.id)}><span style={{background:l.color}}/>{l.name}</button>)}</div><div className="toggle-row light-enabled"><label htmlFor="light-enabled">{light.name} Light</label><Switch id="light-enabled" disabled={disabled} checked={light.enabled} onCheckedChange={v=>c.changeLight('enabled',v)}/></div><label className="color-row">Light Colour<input aria-label="Light Colour" disabled={disabled} type="color" value={light.color} onChange={e=>c.changeLight('color',e.target.value)}/></label>{range('Intensity',light.power,v=>c.changeLight('power',v),0,15,.1)}{range('Width',light.width,v=>c.changeLight('width',v),.2,8,.1)}{range('Height',light.height,v=>c.changeLight('height',v),.2,8,.1)}<div className="section-heading coordinate-heading"><Move3d size={15}/><h3>Position</h3></div>{(['X','Y','Z'] as const).map((axis,i)=><div key={axis}>{range(light.name+' · '+axis,light.position[i],v=>{const position=[...light.position] as Vec3;position[i]=v;c.changeLight('position',position)},-10,10,.1)}</div>)}<button disabled={disabled} className={'secondary-button full '+(p.splitLights?'active':'')} onClick={()=>c.pref('splitLights',!p.splitLights)}><Move3d size={16}/>{p.splitLights?'Close lighting view':'Split lighting view'}</button><p className="control-hint">See the render and light positions together. Click a light panel, then drag its axes.</p><button disabled={disabled} className="text-button" onClick={()=>c.update('lights',settingsFor('hero',s,c.device).lights)}><RotateCcw size={13}/>Reset lights</button></section><section><div className="toggle-row"><div><label htmlFor="reflections">Screen Reflections</label><small>Device reflections stay intact</small></div><Switch id="reflections" disabled={disabled} checked={s.reflection} onCheckedChange={v=>c.update('reflection',v)}/></div></section></TabsContent>
 <TabsContent value="look"><section><div className="section-heading"><Orbit size={16}/><h3>Environment</h3></div>{choice('Preset',s.environment,v=>c.update('environment',v as Settings['environment']),[...ENVIRONMENTS.map(e=>({value:e.id,label:e.name})),...(c.hdrName?[{value:'custom',label:c.hdrName}]:[])])}<button className="secondary-button full" disabled={disabled} onClick={()=>hdrFile.current?.click()}><Upload size={15}/>Upload HDRI</button><input ref={hdrFile} type="file" hidden accept=".hdr,.exr" onChange={e=>{c.uploadHDR(e.target.files?.[0]);e.target.value=''}}/><p className="control-hint">.HDR or .EXR · up to 50 MB / 8K</p>{range('Environment Intensity',s.envIntensity,v=>c.update('envIntensity',v),0,3,.1)}{range('Environment Rotation',s.envRotation,v=>c.update('envRotation',v),-180,180,1,'°')}<div className="toggle-row"><label htmlFor="show-environment">Show HDRI Background</label><Switch id="show-environment" disabled={disabled||s.environment==='none'} checked={s.envBackground} onCheckedChange={v=>c.update('envBackground',v)}/></div>{s.envBackground&&range('Background Blur',s.envBlur,v=>c.update('envBlur',v),0,1,.1)}{s.environment!=='none'?<HDRIEditor c={c}/>:<p className="control-hint">Environment lighting is off. Scene Lights remain active.</p>}<p className="control-hint">Show the HDRI behind the device; lower Background Blur to see the photograph clearly. Transparent PNG exports still have no background. The sun button changes the plain background when this is off.</p></section>

 <section><div className="toggle-row"><label htmlFor="outline-glow">Outline Glow</label><Switch id="outline-glow" disabled={disabled} checked={s.glowEnabled} onCheckedChange={v=>c.update('glowEnabled',v)}/></div>{s.glowEnabled&&<><label className="color-row">Glow Colour<input aria-label="Glow Colour" disabled={disabled} type="color" value={s.glowColor} onChange={e=>c.update('glowColor',e.target.value)}/></label>{range('Glow Intensity',s.glowStrength,v=>c.update('glowStrength',v),.1,3,.1)}{range('Glow Spread',s.glowWidth,v=>c.update('glowWidth',v),1,24,1)}</>}</section><section><div className="section-heading"><SlidersHorizontal size={16}/><h3>Image Treatment</h3></div>{choice('Tone Mapping',s.toneMapping,v=>c.update('toneMapping',v as Settings['toneMapping']),[{value:'aces',label:'ACES · Cinematic'},{value:'agx',label:'AgX · Soft Highlights'},{value:'neutral',label:'Product · Neutral'}])}{range('Exposure',s.exposure,v=>c.update('exposure',v),.2,2.5,.1)}{range('Screen Brightness',s.screenBrightness,v=>c.update('screenBrightness',v),.4,1.6,.1)}</section></TabsContent>
 <TabsContent value="camera"><section><div className="section-heading"><Orbit size={16}/><h3>360° Angles</h3></div><div className="orbit-presets">{ORBIT_ANGLES.map(angle=><button disabled={disabled} key={angle} className={Math.abs(((c.liveCamera.azimuth-angle+540)%360)-180)<.2?'selected':''} onClick={()=>c.applyOrbit(angle)}>{angle}°</button>)}</div><p className="control-hint">Each angle recentres the device and includes matching lights.</p></section><section><div className="section-heading"><Camera size={16}/><h3>Camera Presets</h3></div><div className="camera-presets">{CAMERA_PRESETS.map(preset=><button disabled={disabled} key={preset.id} className={c.viewName===preset.name?'selected':''} onClick={()=>c.applyPreset(preset.id)}><Camera size={18}/><span>{preset.name}</span></button>)}</div>{choice('Projection',c.camera.projection,v=>c.engine.current?.setProjection(v as 'perspective'|'orthographic'),[{value:'perspective',label:'Perspective'},{value:'orthographic',label:'Orthographic'}])}{c.camera.projection==='perspective'?range('Field of View',s.fov,v=>c.update('fov',v),15,70,1,'°'):<p className="control-hint">Parallel projection. Scroll to adjust framing.</p>}{range('Device Roll',s.roll,v=>c.update('roll',v),-180,180,1,'°')}<button disabled={disabled} className="secondary-button full" onClick={()=>c.applyPreset('hero')}><RotateCcw size={15}/>Reset camera & lights</button></section></TabsContent>
 </div></Tabs><Collapsible className="export-panel" open={!p.exportCollapsed} onOpenChange={v=>c.pref('exportCollapsed',!v)}><CollapsibleTrigger className="export-heading"><span><Download size={15}/>Export <small>PNG</small></span>{p.exportCollapsed?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</CollapsibleTrigger><CollapsibleContent>{c.lastDownload&&<button className="secondary-button full" onClick={c.downloadAgain}><Download size={14}/>Download ZIP again</button>}{choice('Resolution',c.resolution,c.setResolution,['1200','2400','4096'].map(v=>({value:v,label:v+' × '+v})))}<div className="toggle-row"><label htmlFor="transparent">Transparent Background</label><Switch id="transparent" disabled={disabled} checked={c.transparent} onCheckedChange={c.setTransparent}/></div>{!c.transparent&&!s.envBackground&&<label className="color-row">Background<input aria-label="Export background colour" disabled={disabled} type="color" value={s.background} onChange={e=>c.update('background',e.target.value)}/></label>}<ExportNamingControls c={c}/><button className="export wide" disabled={!c.ready||disabled} onClick={c.exportPNG}><Download size={16}/>Export image</button>{c.selected.size>1&&<button className="export wide" disabled={!c.ready||disabled} onClick={()=>c.exportBatch(c.scenes.filter(scene=>c.selected.has(scene.id)),'Divices scenes')}><Download size={16}/>Export {c.selected.size} selected</button>}<p className="control-hint">Fits the full device. Scene and kit ZIPs use this resolution.</p></CollapsibleContent></Collapsible></aside>;
}
