'use client';
import {useEffect,useRef} from 'react';
import {flushSync} from 'react-dom';
import {DEVICES,ENVIRONMENTS,CAMERA_PRESETS,ORBIT_ANGLES,type CameraPreset,type Settings} from './studio-config';
import type {DivicesController} from './use-divices';
export function useSceneTools(controller:DivicesController){
 const current=useRef(controller);current.current=controller;
 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context)return;
  const lifecycle=new AbortController(),register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}};
  const available=()=>{const c=current.current;if(!c.ready||c.busy||c.loading)throw new Error('Wait for the scene to finish loading.');return c};
  register({name:'read_scene',description:'Read the current device, camera, lighting, effects, scene library and viewport preferences.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>{const c=current.current;return {device:c.device,settings:c.settings,camera:c.engine.current?.captureCamera(),preferences:c.preferences,scenes:c.scenes.map(s=>({id:s.id,name:s.name,folderId:s.folderId,device:s.snapshot.device})),folders:c.folders,ready:c.ready,loading:c.loading,busy:c.busy,progress:c.progress,message:c.message,error:c.error,lastArchive:c.lastDownload?{name:c.lastDownload.name,bytes:c.lastDownload.blob.size}:null,renderError:c.engine.current?.renderError,lastExport:c.engine.current?.lastExport}}});
  register({name:'set_camera_orbit',description:'Centre the device at an orbit preset with matching lighting.',inputSchema:{type:'object',properties:{angle:{type:'number',enum:ORBIT_ANGLES}},required:['angle'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(a:{angle:number})=>{const c=available();if(!a||Object.keys(a).some(k=>k!=='angle')||!ORBIT_ANGLES.some(v=>v===a.angle))throw new Error('Choose a supported orbit angle.');flushSync(()=>c.applyOrbit(a.angle));return c.engine.current!.captureCamera()}});
  register({name:'configure_scene',description:'Adjust the device, camera, lighting and viewport preferences using the same controls as the interface.',inputSchema:{type:'object',properties:{device:{type:'string',enum:DEVICES.map(d=>d.id)},cameraPreset:{type:'string',enum:CAMERA_PRESETS.map(p=>p.id)},fov:{type:'number',minimum:15,maximum:70},deviceColor:{type:'string',pattern:'^#[0-9a-fA-F]{6}$'},environment:{type:'string',enum:ENVIRONMENTS.map(e=>e.id)},screenReflections:{type:'boolean'},lightBackground:{type:'boolean'},splitLights:{type:'boolean'},exportCollapsed:{type:'boolean'}},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(a:Record<string,unknown>)=>{
   const c=available();if(!a||typeof a!=='object'||Object.keys(a).some(k=>!['device','cameraPreset','fov','deviceColor','environment','screenReflections','lightBackground','splitLights','exportCollapsed'].includes(k)))throw new Error('Invalid scene settings.');
   if((a.device!==undefined&&!DEVICES.some(d=>d.id===a.device))||(a.cameraPreset!==undefined&&!CAMERA_PRESETS.some(p=>p.id===a.cameraPreset))||(a.fov!==undefined&&(typeof a.fov!=='number'||!Number.isFinite(a.fov)||a.fov<15||a.fov>70))||(a.deviceColor!==undefined&&(typeof a.deviceColor!=='string'||!/^#[\da-f]{6}$/i.test(a.deviceColor)))||(a.environment!==undefined&&!ENVIRONMENTS.some(e=>e.id===a.environment))||['screenReflections','lightBackground','splitLights','exportCollapsed'].some(k=>a[k]!==undefined&&typeof a[k]!=='boolean'))throw new Error('Invalid scene settings.');
   if(a.device)await c.chooseDevice(a.device as string);
   flushSync(()=>{if(a.cameraPreset)c.applyPreset(a.cameraPreset as CameraPreset);if(a.fov!==undefined)c.update('fov',a.fov as number);if(a.deviceColor)c.update('deviceColor',a.deviceColor as string);if(a.environment)c.update('environment',a.environment as Settings['environment']);if(a.screenReflections!==undefined)c.update('reflection',a.screenReflections as boolean);for(const key of ['lightBackground','splitLights','exportCollapsed'] as const)if(a[key]!==undefined)c.pref(key,a[key] as boolean)});
   c.engine.current!.configure(current.current.settings);await c.engine.current!.readyToRender();return {device:current.current.device,settings:current.current.settings,preferences:current.current.preferences};
  }});
  register({name:'save_scene',description:'Create a named scene from the current setup, starting with a green screen.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:1,maxLength:80}},required:['name'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(a:{name:string})=>{const c=available();if(!a||typeof a.name!=='string'||!a.name.trim()||a.name.length>80)throw new Error('Enter a scene name of 1–80 characters.');const record=await c.saveCurrent(a.name,null);return {id:record.id,name:record.name}}});
  register({name:'load_scene',description:'Load a previously saved scene.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(a:{id:string})=>{const c=available();if(!a||typeof a.id!=='string')throw new Error('Choose a saved scene.');return c.loadScene(a.id)}});
  return()=>lifecycle.abort();
 },[]);
}
